### PR TITLE
Bump for 0.0.3 release: breaking changes!

### LINKED ISSUE #38: exclude mountpoint / root volume from being snapshotted
Correct me if I'm wrong, but I think there's no option currently to exclude the root volume a.k.a. the mountpoint from being snapshotted. The exclude patterns file only applies to subvolumes, and as they don't have a leading `/` one couldn't specify the root to be excluded at all.

I like to have a somewhat flat subvolume layout, where a subvolume of the root volume is mounted as `/`, not the root volume itself, while the root volume is only used to contain the other subvolumes, but not mounted in the filesystem hierarchy.
See https://btrfs.wiki.kernel.org/index.php/SysadminGuide#Layout for more details so I don't have to repeat them here. :wink:

I'm not sure what to do here, though. Options that came to my mind, in no particular order:
- add a command line option like `snazzer --ignore-mountpoint`
- prefix all subvolumes listed by `btrfs subvolume list -t` with a `/`, so that one's able to specify `/` in the snazzer exclude file. This would require a change in all absolute paths in the exclude file, but might improve usability as people would probably throw in the leading `/` anyway if they're not familiar with the format of `sudo btrfs subvolume list`.
- Do nothing at all and just accept that there's an unneeded `/.snapshotz` full of snapshots that never change at all.

I'm currently using my own fork that has mounpoint snapshotting disabled in the code, but that's no general solution, of course. :wink:

### PR DESCRIPTION
**Pull request by csirac2**
Breaking changes to fix https://github.com/csirac2/snazzer/issues/38:

    exclude mountpoint / root volume from being snapshotted

### CODE REVIEW

**Comment by csirac2** [comment]
If this looks good to you @florianjacob let's merge & tag it for release

**Comment by florianjacob** [comment]
Looks fine to me! Only added some minor changelog improvements (mainly linked the section titles to the diffs).

I think the travis fail can be safely ignored for now, as it seems to be some artifact from the version bump.

I'll merge this and tag it now. 😄 🚢

**Comment by csirac2** [comment]
Yeah I should probably fix that: my CHANGELOG.md sanity check didn't cater to building an untagged branch... d'oh.

**Comment by florianjacob** [comment]
Oh right, now I see. 👍

**Pull request merged**
