### PR TITLE
preliminary 0.0.1 release

### PR DESCRIPTION
**Pull request by florianjacob**
including changelog template for 0.1 release.

### CODE REVIEW

**Comment by csirac2** [comment]
I've pushed a couple of commits to sync `SNAZZER_VERSION` and also added a `--version` switch everywhere so that version info is useful. If you're okay with that, please feel free to merge. Note that we'll have to push another `0.0.1` tag...

**Comment by csirac2** [comment]
There are some problems with the current release workflow: we need to tag master, rather than push tags on branches. Please excuse the commit noise while I figure things out...

**Comment by florianjacob** [comment]
No problem. I think the tag will point to the commit in the master branch as soon as this would be merged?

**Comment by florianjacob** [comment]
Completely missed the existing version variable, looks good!
If my travis fix works out, I'll merge this to master and see whether something still needs to be done regarding tags.

**Comment by csirac2** [comment]
Ok, we can evolve the release procedure and undo my CHANGELOG.md sanity checks later if it's deemed necessary. Feel free to merge this for now.

My concern with tagging feature branches:
- tags exist separately to branches. Whenever you push a tag to csirac2/snazzer, that is creating a release as far as github is concerned ;-) (even before a PR is accepted - that's why I did 0.0.2, but we can throw away both tags, who is going to download snazzer at this time of year?)
- the git commit id you tag on a local feature branch can only be the same git commit id that ends up in the remote release branch (master) IFF the merge can be squashed/fast-forwarded.
- ... which won't be true if you forget to rebase your feature branch on top of the latest master prior to tagging locally (Eg. during an "accept multiple PRs" spree). So basically, tagging local feature branches has a risk of creating dangling tags that point to a commit that only exists on your local checkout

But we can think about this later. Cheers!

**Comment by florianjacob** [comment]
Now I understand, thanks for the explanations. 👍

Then, let's do the release. 😄 Cheers!

**Pull request merged**
